### ISSUE TITLE
Kicad ground pours split 

### ISSUE THREAD

**Issue by mwudka** [MakeraInc/MakeraCAM#1]
I made a simple test layout witha couple of copper pours that I think might have confused MakeraCAM. I've attached the kicad 8.0 project and gerbers for reproducing, but in short I have the following layout:

<img width="934" alt="image" src="https://github.com/MakeraInc/MakeraCAM/assets/788355/f7bd9242-6439-4551-a937-7582e94fc860">

CopperCAM almost handles this file correctly, except for a spurious and incorrect extra hatching line (note the thin blue line that would incorrectly split the GND plane in two:

<img width="1612" alt="image" src="https://github.com/MakeraInc/MakeraCAM/assets/788355/2c5c1436-ef44-40e7-8d6a-d853c940e517">

MakeraCAM gets quite confused, however:

<img width="1043" alt="image" src="https://github.com/MakeraInc/MakeraCAM/assets/788355/61d14676-23be-4045-ac53-0bcbc15ea67d">

The smaller horizontal pour is split in two and isolated from the VDD pin on the chip. All of the non-power pins on the ship should be isolated, but they are all tied together. There are also a few stray additional cuts that shouldn't exist.

[makeracam-tests.zip](https://github.com/MakeraInc/MakeraCAM/files/14910030/makeracam-tests.zip)

**Comment by leighost24** [comment]
We will fix this issue in the next version.
