### ISSUE TITLE
Changing tool number doesn't keep when editing existing pocket toolpath

### ISSUE THREAD

**Issue by faecorrigan** [MakeraInc/MakeraCAM#12]
Steps to reproduce: 

1. create a vector - pocket toolpath and choose a single tool
2. calculate and close the wizard
3. right click the tool path in the outliner and edit
4. change the tool number and hit calculate again. the tool number in the outliner will not update and when you close the wizard and edit again the tool number will have reset to the original value

This is not a problem with drill toolpaths as the tool number there updates, I have not tested contour paths
The image shows the status after hitting calculate where the tool number is changed in the wizard but has not updated in the path outliner
![image](https://github.com/MakeraInc/MakeraCAM/assets/145371008/255f67ac-7fd7-4b85-a9f6-c7be68cd569b)

**Comment by leighost24** [comment]
Fixed in V0.1.2.0
