### ISSUE TITLE
Resizing outliner does not work

### ISSUE THREAD

**Issue by faecorrigan** [MakeraInc/MakeraCAM#13]
When hovering over the border between the outliner and viewport a widget appears to resize the outliner but does not function. It would be very useful to be able to resize both the outliner and wizard (right side of screen) UI elements.

![image](https://github.com/MakeraInc/MakeraCAM/assets/145371008/c514a197-4fca-478f-bf48-dc685592d5cc)

**Comment by leighost24** [comment]
Fixed in V0.1.2.0
