### ISSUE TITLE
Editing stock user functionality

### ISSUE THREAD

**Issue by faecorrigan** [MakeraInc/MakeraCAM#14]
When editing stock fields when the user hits enter/tab/leaves a field (usually called onTextCommitted) it should fire the same command as the ok button to update the stock in the viewport so that you don't have to re click edit each time you want to see a stock change. 

![image](https://github.com/MakeraInc/MakeraCAM/assets/145371008/014aec06-af5a-478f-9ca2-9b4abf3a9cc7)

**Comment by leighost24** [comment]
Fixed in V0.1.2.0
