### ISSUE TITLE
Drill files imported from Fusion Electronics (Eagle) throwing 'non-closed graphic' error

### ISSUE THREAD

**Issue by orbiandy** [MakeraInc/MakeraCAM#17]
After selecting a set of drill circles and setting up a vector pocket, I'm seeing an error: There is a non-closed graphic in the selected graphic, and the area clearing tool path cannot be generated! - Problem is, this does not appear to be true - holes are all circles and appear to be closed. Drill file and screenshot attached. MakeraCAM Version  0.1.1.0  (Beta)

[drill_1_16.txt](https://github.com/MakeraInc/MakeraCAM/files/15445008/drill_1_16.txt)
![2024-05-25 16_44_54-MakeraCAM- EP3-10-10-rules](https://github.com/MakeraInc/MakeraCAM/assets/170822799/74727f9b-348c-4e6e-bce9-9dc0b75b75d5)

**Comment by leighost24** [comment]
This issue has been resolved in the latest development version. Please look forward to the next release version.
![image](https://github.com/MakeraInc/MakeraCAM/assets/55370592/fe00c17f-e862-42da-aef1-4cb9540a1fba)
