### ISSUE TITLE
compile for apple silicon

### ISSUE THREAD

**Issue by lemontron** [MakeraInc/MakeraCAM#20]
I don't know who needs to hear this but this software is outdated on day 1. Even crusty Fusion 360 supports apple silicon now, meaning rosetta is no longer needed. it's not a good look to be coming out in 2024, and already be a relic from pre-apple silicon era (ui looking extra deep fried too)

![Screenshot 2024-07-10 at 8 14 15 AM](https://github.com/MakeraInc/MakeraCAM/assets/8919598/57bf5340-8593-4667-9b88-c019e387826c)

**Comment by leighost24** [comment]
Considering that many users are still using the Intel version of early Macs, this setting is for compatibility with Intel chips, and the M series ARM chips are also supported.

Welcome to join Makera's Discord discussion group, where you'll find many like-minded friends to discuss related topics together.
https://discord.gg/hRmF6FDx

**Comment by gskluzacek** [comment]
I too was surprised and a little disappointed that MakeraCAM was running under Rosetta-2...

from the activity monitor... looks like there is no process name for MakeraCAM either (strange)

![Image](https://github.com/user-attachments/assets/86e2292e-3494-4cd3-9672-d9227465e583)

but I could verify that it was MakeraCAM by inspecting the process

![Image](https://github.com/user-attachments/assets/5bb81b8a-559c-4385-a7a0-64f2830c339c)

I guess it was announced at WWDC 2025 that after macOS 26 Tahoe (i.e., macOS 27 and later) apple is dropping support for Intel based Macs. And that macOS 28 will not (fully) support Rosetta (only will be supported for some legacy games).

![Image](https://github.com/user-attachments/assets/a512b407-510f-43cc-8085-2d448cc8d173)

![Image](https://github.com/user-attachments/assets/78877046-680a-4349-9a29-a97e26aa98e6)
