### ISSUE TITLE
Can't delete a layer if it's selected

### ISSUE THREAD

**Issue by shaun-leach** [MakeraInc/MakeraCAM#4]
Create a new project.
Add a second layer
Select that layer
Right click on the selected layer and select delete
Layer doesn't delete

Expected result: The layer is deleted

**Comment by leighost24** [comment]
When a new layer is inserted, the new layer will automatically switch to the active layer. The program logic setting cannot delete the currently activated layer. We will provide a front-end prompt for this operation in future versions.

**Comment by leighost24** [comment]
When a new layer is inserted, the new layer will automatically switch to the active layer. The program logic setting cannot delete the currently activated layer. We will provide a front-end prompt for this operation in future versions.
