### ISSUE TITLE
Most Pads are missing when importing this gerber

### ISSUE THREAD

**Issue by shaun-leach** [MakeraInc/MakeraCAM#5]
[ContinuitySMT-F_Cu.zip](https://github.com/MakeraInc/MakeraCAM/files/14968941/ContinuitySMT-F_Cu.zip)
<img width="566" alt="MakeraCAMMissingPads" src="https://github.com/MakeraInc/MakeraCAM/assets/5731563/2999bfe2-99ef-4428-8429-db20ba580d2c">
![Screenshot 2024-04-13 161716](https://github.com/MakeraInc/MakeraCAM/assets/5731563/f83bd969-c29c-43f1-b127-42260390c31b)

Compare the MakeraCAM version, magenta & black vs the FlatCAM version, yellow & red

**Comment by sedivy74** [comment]
I am facing the same problem - a pad is missing
[PwrSrc5VModule-B_Cu.gbr.zip](https://github.com/MakeraInc/MakeraCAM/files/15048338/PwrSrc5VModule-B_Cu.gbr.zip)
MakeraCAM and Gerbview comparison
![Screenshot from 2024-04-20 15-26-03](https://github.com/MakeraInc/MakeraCAM/assets/102593212/f3bf42ae-5f8b-4a77-85eb-4aa0bf929c3a)
![Screenshot from 2024-04-20 15-26-40](https://github.com/MakeraInc/MakeraCAM/assets/102593212/40196886-0170-4fa7-98f1-d79e788c6ec6)
