### ISSUE TITLE
Mask file not importing correctly.

### ISSUE THREAD

**Issue by shaun-leach** [MakeraInc/MakeraCAM#7]
[ContinuitySMT-F_Mask.zip](https://github.com/MakeraInc/MakeraCAM/files/15054822/ContinuitySMT-F_Mask.zip)

Importing this mask file creates two layers. One appears to be correct. The other one is missing some of the pads.

**Comment by leighost24** [comment]
To facilitate user machining, the solder mask or pads have been extracted from the file. An independent layer will be displayed based on the complete circuit layer. If there is no need to process this information, you can hide or delete the layer information with a suffix of "pad" after the file has been loaded.
