### ISSUE TITLE
Layers wisibility

### ISSUE THREAD

**Issue by sedivy74** [MakeraInc/MakeraCAM#9]
Enabling/disabling layers view sometimes does not work (layers are visible despite of disabling it)
![Screenshot from 2024-04-25 22-26-25](https://github.com/MakeraInc/MakeraCAM/assets/102593212/b07b3838-6ae5-4e35-8273-bae6d1176312)
Second group of layers (Top in attached file) is not sometimes not visible when switched elsewhere (grayed)
![Screenshot from 2024-04-25 22-37-13](https://github.com/MakeraInc/MakeraCAM/assets/102593212/bf06db14-f9de-48ce-8e36-5707c3b5f586)
![Screenshot from 2024-04-25 22-37-25](https://github.com/MakeraInc/MakeraCAM/assets/102593212/d28e7d1a-238f-436a-852a-3e889ca2adc6)

[DataIssue.zip](https://github.com/MakeraInc/MakeraCAM/files/15120505/DataIssue.zip)
)

**Comment by leighost24** [comment]
Fixed in V0.1.2.0
